### ISSUE TITLE
A better name?

### ISSUE THREAD

**Issue by Tpt** [Tpt/rudf#15]
_Rudf_ is not a very nice name. It might be better to pick a new one.

I have no good idea yet. I was maybe thinking about _FastR_ (pronounced _faster_, acronym-like for _fast relations_ or _fast RDF_) but it sounds a lot like a library for the _R_ programming language.

@dwhitney Do you have any idea/opinion about it? It would be much welcome

**Comment by dwhitney** [comment]
sparql_rs?  I dunno - you should be the one who names it!

**Comment by Tpt** [comment]
I would like to find something that is to too strongly connected to Rust because I hope it will make sense to use this library in the future even without wanting to have something "in Rust".

What about _Oxygraph_? It emphases the main goal of this project (a graph database) with a reference to Rust (the "oxidation" part). What do you think about it?

**Comment by dwhitney** [comment]
I like your point about using it contexts other than rust. Yesterday I got
it running in webassembly. It's lightning fast (in webkit based browsers)
compared to a JavaScript engine I was using! (As an aside there were a
couple of minor modifications I had to make to get it working - I'll make
as issue).

Oxygraph is pretty good! It doesn't really highlight SPARQL, but I guess
that is fine

**Comment by Tpt** [comment]
> Yesterday I got it running in webassembly. It's lightning fast (in webkit based browsers) compared to a JavaScript engine I was using! 

Great! Congrats! Please make a PR/open issues for the problems. After all problems are fixed, it would be nice to have a CI job that checks if the project builds on WebAssembly.

> It doesn't really highlight SPARQL

Indeed, but fitting such a big acronym is difficult. There is maybe something to do with "sparkle" and "oxid" but I have no idea. If you have an idea, it is much welcome.

**Comment by Tpt** [comment]
Let's settle to _oxigraph_ for now (with an _i_ for _oxid_ and not a _y_ for _oxygen_). I have updated the code and the repository name. @dwhitney feel free to open this task again if you think of something better.
