### ISSUE TITLE
Implement a disk-based dataset store

### ISSUE THREAD

**Issue by Tpt** [Tpt/rudf#5]
We should first investigate on which backend use. Some ideas:

* [RocksDB](https://rocksdb.org/)
* [FoundationDB](https://www.foundationdb.org/)

**Comment by tobias47n9e** [comment]
Wouod postgres key-value store be possible? It has some rust support:

https://www.postgresql.org/docs/current/static/hstore.html

https://github.com/diesel-rs/diesel/issues/970

**Comment by Tpt** [comment]
Yes, it would be possible indeed. But Postgres hstore store seems more targeted at providing a way to extend table rows, not at providing a fast key-value store. I believe that if we want to use postgres as backend we should use instead tables and regular indexes. Key and values in hstore are also always stored as strings, and it does not seems very good for efficient storage, especially for numerical datatypes.

**Comment by Tpt** [comment]
Done with `RocksDBRepository`
