### ISSUE TITLE
Bug in use of prefixes in SPARQL queries

### ISSUE THREAD

**Issue by dwhitney** [Tpt/rudf#9]
I found a bug when using prefixes in queries - essentially if you use prefixes, the query doesn't find anything. I've created a branch called [prefix-bug](https://github.com/dwhitney/rudf/tree/prefix-bug) in my fork that is current with `master`, but adds a [test](https://github.com/dwhitney/rudf/blob/prefix-bug/lib/tests/prefix_bug_test_cases.rs) to illustrated the bug. It uses the two queries below, which should produce the same results, but the test fails because of the bug.

```sparql
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
SELECT ?name ?mbox
WHERE
  { 
    ?s <foaf:name> ?name .
    ?s <foaf:mbox> ?mbox .
  }
```

```sparql
SELECT ?name ?mbox
WHERE
  { 
    ?s <http://xmlns.com/foaf/0.1/name> ?name .
    ?s <http://xmlns.com/foaf/0.1/mbox> ?mbox .
  }
```

**Comment by Tpt** [comment]
Hi! Sorry for the late answer. It's not a bug, prefixes query should not be enclosed in`<>`.

This query should work:
```
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
SELECT ?name ?mbox
WHERE
  { 
    ?s foaf:name ?name .
    ?s foaf:mbox ?mbox .
  }
```

**Comment by dwhitney** [comment]
Derp thanks. I'll close this issue when I'm at my desk. Any chance you
could take a look at me last question on the other issue?

**Comment by dwhitney** [comment]
yes, that resolved my issue. thanks for the second pair of eyes!
